version: '3.8'

services:
  frontend:
    build:
      context: "."
      no_cache: true
    ports:
      - "63723:4321"
    env_file: .env
    environment:
      - PORT=4321
      - HOST=0.0.0.0
    networks:
      - zecas
